services:
  payments-service-postgresql:
    container_name: payments-service-postgresql
    image: postgres:17.2
    ports:
      - ${DATABASE_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - payments-service-network
    volumes:
      - payments_service_pg_data:/var/lib/postgresql/data

  payments-service-postgresql-test:
    container_name: payments-service-postgresql-test
    image: postgres:17.2
    profiles:
      - test
    ports:
      - ${DATABASE_TEST_PORT:-5434}:5432
    environment:
      POSTGRES_USER: ${DATABASE_TEST_USERNAME:-test}
      POSTGRES_PASSWORD: ${DATABASE_TEST_PASSWORD:-test}
      POSTGRES_DB: ${DATABASE_TEST_NAME:-payments_test}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_TEST_USERNAME:-test} -d ${DATABASE_TEST_NAME:-payments_test}",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - payments-service-network

  payments-service-rabbitmq-test:
    container_name: payments-service-rabbitmq-test
    image: rabbitmq:4.3.4-management-alpine
    profiles:
      - test
    ports:
      - ${RABBITMQ_TEST_PORT:-5673}:5672
      - ${RABBITMQ_TEST_MANAGEMENT_PORT:-15673}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_TEST_USER:-test}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_TEST_PASSWORD:-test}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - payments-service-network

networks:
  payments-service-network:
    driver: bridge

volumes:
  payments_service_pg_data:
